# Generated by Django 4.1.4 on 2022-12-20 13:30

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Список продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=70, null=True, populate_from='name', unique=True),
        ),
    ]
